// File generated by hand for the EsportMGM project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // If you want to support web, you'''ll need to add a web app in Firebase
      // and create a 'web' static const like the 'android' one below.
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can re-run this command with the --web flag',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can re-run this command with the --ios-bundle-id flag',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can re-run this command with the --macos-bundle-id flag',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can re-run this command with the --windows-app-id flag',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can re-run this command with the --linux-app-id flag',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PASTE_YOUR_WEB_API_KEY_HERE',
    appId: '1:842502464869:android:01498628a7223ea3b3ed8c', // This is from you!
    messagingSenderId: 'PASTE_YOUR_PROJECT_NUMBER_HERE',
    projectId: 'PASTE_YOUR_PROJECT_ID_HERE',
    storageBucket: 'PASTE_YOUR_PROJECT_ID_HERE.appspot.com',
  );
}
